- ros_topic_name: "/scan"
  gz_topic_name: "/unilidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/unilidar/cloud"
  gz_topic_name: "/unilidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/zed/image_raw"
  gz_topic_name: "/world/warehouse/model/turtlebot4/link/zed_left_camera_frame/sensor/zed_rgbd/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS